apiVersion: v1
kind: Service
metadata:
  name: gov-route-library
  labels:
    app: gov-route-library
    component: frontend
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: gov-route-library
    component: frontend
